### ISSUE TITLE
Feature: Registration Page

### ISSUE THREAD

**Issue by andhikayusup** [andhikayusup/anglika-react-client#1]
#### Description
A user register an account. The required input to perform this action is email, password, and full name. If user already have email registered then they cannot register their account with the email. After account is successfully registered, user should automatically logged in. The account should be activated by the link provided with their account's email. Until then, they cannot use the account. 

#### Tasks
- [x] Initialize GraphQL server
- [ ] Initialize and set up MongoDB Atlas
- [ ] Create typeDefs for user Type and register Mutation.
- [ ] Create resolver for user account Query 
- [ ] Create resolver for account registration Mutation
- [ ] Create resolver for sending activation link to the registered email Mutation.
